plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

remote_theme: vszhub/not-pure-poole

# Setup
title: "[EPPS 6302] SolB's Project"
description: "2025 Fall - [EPPS 6302] Methods of Data Collection and Production"
url: https://solb-kim.github.io/EPPS6302/
avatar: /assets/hobak.jpg
paginate: 6
permalink: pretty
cover_image: /assets/bg.jpg

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyll SEO Tag
sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

